# Generated by Django 5.2 on 2025-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_closure_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="closure",
            name="depth",
            field=models.IntegerField(null=True),
        ),
    ]
