# Generated by Django 5.2 on 2025-05-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_create_materialized_view"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"managed": False},
        ),
    ]
