# Generated by Django 5.2 on 2025-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_unit_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitHierarchy",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("parent_id", models.IntegerField(blank=True, null=True)),
                ("depth", models.IntegerField()),
            ],
            options={
                "db_table": "unit_hierarchy",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={},
        ),
    ]
